import { Product, Customer } from "@/db/schema";
import { BusinessArchetype } from "@/context/BusinessModeContext";

export function getStarterProducts(businessType: BusinessArchetype, organizationId: string): Product[] {
  const now = new Date();
  
  switch (businessType) {
    case "FNB":
      return [
        {
          id: `prod-fnb-1-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Kopi Susu Gula Aren",
          sku: "FNB-001",
          barcode: "8990001001",
          category: "Minuman",
          costPrice: "8000",
          sellingPrice: "18000",
          wholesalePrice: "15000",
          minWholesaleQty: 10,
          stock: 60,
          unit: "cup",
          minStockAlert: 10,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-fnb-2-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Espresso Single Shot",
          sku: "FNB-002",
          barcode: "8990001002",
          category: "Minuman",
          costPrice: "4000",
          sellingPrice: "12000",
          wholesalePrice: "10000",
          minWholesaleQty: 10,
          stock: 100,
          unit: "cup",
          minStockAlert: 15,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-fnb-3-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Croissant Butter Original",
          sku: "FNB-003",
          barcode: "8990001003",
          category: "Makanan",
          costPrice: "12000",
          sellingPrice: "24000",
          wholesalePrice: "20000",
          minWholesaleQty: 5,
          stock: 30,
          unit: "pcs",
          minStockAlert: 5,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-fnb-4-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "French Fries Crispy",
          sku: "FNB-004",
          barcode: "8990001004",
          category: "Camilan",
          costPrice: "7000",
          sellingPrice: "16000",
          wholesalePrice: "13000",
          minWholesaleQty: 5,
          stock: 40,
          unit: "porsi",
          minStockAlert: 5,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
      ];

    case "RETAIL":
      return [
        {
          id: `prod-ret-1-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Beras Premium 5kg",
          sku: "RET-001",
          barcode: "8992001001",
          category: "Sembako",
          costPrice: "65000",
          sellingPrice: "74000",
          wholesalePrice: "70000",
          minWholesaleQty: 5,
          stock: 45,
          unit: "sak",
          minStockAlert: 10,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-ret-2-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Minyak Goreng 2 Liter",
          sku: "RET-002",
          barcode: "8992001002",
          category: "Sembako",
          costPrice: "28000",
          sellingPrice: "34000",
          wholesalePrice: "31000",
          minWholesaleQty: 6,
          stock: 80,
          unit: "pouch",
          minStockAlert: 12,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-ret-3-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Air Mineral Botol 600ml",
          sku: "RET-003",
          barcode: "8992001003",
          category: "Minuman",
          costPrice: "2500",
          sellingPrice: "5000",
          wholesalePrice: "4000",
          minWholesaleQty: 24,
          stock: 120,
          unit: "botol",
          minStockAlert: 24,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-ret-4-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Keripik Singkong Balado",
          sku: "RET-004",
          barcode: "8992001004",
          category: "Snack",
          costPrice: "8500",
          sellingPrice: "14000",
          wholesalePrice: "11500",
          minWholesaleQty: 10,
          stock: 50,
          unit: "bks",
          minStockAlert: 10,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
      ];

    case "SALON":
      return [
        {
          id: `prod-sal-1-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Haircut & Styling Gentleman",
          sku: "SAL-001",
          barcode: "8993001001",
          category: "Layanan Pria",
          costPrice: "10000",
          sellingPrice: "50000",
          wholesalePrice: null,
          minWholesaleQty: 1,
          stock: 999,
          unit: "sesi",
          minStockAlert: 5,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-sal-2-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Creambath Spa & Pijat Kepala",
          sku: "SAL-002",
          barcode: "8993001002",
          category: "Treatment",
          costPrice: "20000",
          sellingPrice: "85000",
          wholesalePrice: null,
          minWholesaleQty: 1,
          stock: 999,
          unit: "sesi",
          minStockAlert: 5,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-sal-3-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Pomade Oil-Based 100gr",
          sku: "SAL-003",
          barcode: "8993001003",
          category: "Produk Styling",
          costPrice: "35000",
          sellingPrice: "65000",
          wholesalePrice: "50000",
          minWholesaleQty: 6,
          stock: 25,
          unit: "jar",
          minStockAlert: 5,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
      ];

    case "SERVICES":
      return [
        {
          id: `prod-srv-1-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Ganti Oli Mesin + Filter (Jasa)",
          sku: "SRV-001",
          barcode: "8994001001",
          category: "Jasa Servis",
          costPrice: "10000",
          sellingPrice: "45000",
          wholesalePrice: null,
          minWholesaleQty: 1,
          stock: 999,
          unit: "unit",
          minStockAlert: 5,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-srv-2-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Oli Mesin Sintetik 1 Liter",
          sku: "SRV-002",
          barcode: "8994001002",
          category: "Sparepart & Oli",
          costPrice: "55000",
          sellingPrice: "75000",
          wholesalePrice: "68000",
          minWholesaleQty: 6,
          stock: 40,
          unit: "botol",
          minStockAlert: 8,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-srv-3-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Kampas Rem Depan Cakram",
          sku: "SRV-003",
          barcode: "8994001003",
          category: "Sparepart",
          costPrice: "35000",
          sellingPrice: "55000",
          wholesalePrice: "48000",
          minWholesaleQty: 5,
          stock: 20,
          unit: "set",
          minStockAlert: 4,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
      ];

    case "WHOLESALE":
      return [
        {
          id: `prod-whl-1-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Gula Pasir Kristal 50kg (Sak)",
          sku: "WHL-001",
          barcode: "8995001001",
          category: "Bahan Baku",
          costPrice: "680000",
          sellingPrice: "750000",
          wholesalePrice: "720000",
          minWholesaleQty: 5,
          stock: 50,
          unit: "sak",
          minStockAlert: 10,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-whl-2-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Tepung Terigu Karung 25kg",
          sku: "WHL-002",
          barcode: "8995001002",
          category: "Bahan Baku",
          costPrice: "210000",
          sellingPrice: "245000",
          wholesalePrice: "230000",
          minWholesaleQty: 10,
          stock: 80,
          unit: "karung",
          minStockAlert: 15,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
      ];

    case "HYBRID":
    default:
      return [
        {
          id: `prod-hyb-1-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Kaos Polos Cotton Combed 30s",
          sku: "HYB-001",
          barcode: "8996001001",
          category: "Fashion",
          costPrice: "32000",
          sellingPrice: "65000",
          wholesalePrice: "48000",
          minWholesaleQty: 12,
          stock: 90,
          unit: "pcs",
          minStockAlert: 15,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: `prod-hyb-2-${Date.now()}`,
          organizationId,
          outletId: "outlet-1",
          name: "Totebag Kanvas Premium",
          sku: "HYB-002",
          barcode: "8996001002",
          category: "Aksesoris",
          costPrice: "22000",
          sellingPrice: "45000",
          wholesalePrice: "35000",
          minWholesaleQty: 10,
          stock: 45,
          unit: "pcs",
          minStockAlert: 10,
          imageUrl: "",
          createdAt: now,
          updatedAt: now,
        },
      ];
  }
}

export function getStarterCustomers(organizationId: string): Customer[] {
  const now = new Date();
  return [
    {
      id: `cust-1-${Date.now()}`,
      organizationId,
      name: "Budi Santoso",
      phone: "0812-3456-7890",
      email: "budi@gmail.com",
      address: "Jl. Melati No. 12, Jakarta",
      notes: "Pelanggan VIP / Member Setia",
      tier: "GOLD",
      loyaltyPoints: 150,
      totalSpent: "1450000",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: `cust-2-${Date.now()}`,
      organizationId,
      name: "Siti Rahma",
      phone: "0813-9876-5432",
      email: "siti.rahma@yahoo.com",
      address: "Jl. Kemang Raya No. 45",
      notes: "Member Silver",
      tier: "SILVER",
      loyaltyPoints: 45,
      totalSpent: "450000",
      createdAt: now,
      updatedAt: now,
    },
  ];
}
