import * as schema from './schema';

export * from './schema';

// Initial Mock Dataset for Offline-First / Browser LocalStorage Seeding
export const INITIAL_PRODUCTS: Array<schema.Product> = [
  {
    id: 'prod-1',
    organizationId: 'org-demo-1',
    outletId: 'outlet-1',
    name: 'Kopi Susu Gula Aren',
    sku: 'BEV-001',
    barcode: '899123456001',
    category: 'Minuman',
    costPrice: '8000',
    sellingPrice: '18000',
    wholesalePrice: '15000',
    minWholesaleQty: 10,
    stock: 85,
    unit: 'cup',
    minStockAlert: 10,
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-2',
    organizationId: 'org-demo-1',
    outletId: 'outlet-1',
    name: 'Espresso Single Shot',
    sku: 'BEV-002',
    barcode: '899123456002',
    category: 'Minuman',
    costPrice: '5000',
    sellingPrice: '12000',
    wholesalePrice: '10000',
    minWholesaleQty: 10,
    stock: 120,
    unit: 'cup',
    minStockAlert: 15,
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-3',
    organizationId: 'org-demo-1',
    outletId: 'outlet-1',
    name: 'Croissant Butter Original',
    sku: 'BAK-001',
    barcode: '899123456003',
    category: 'Makanan',
    costPrice: '12000',
    sellingPrice: '24000',
    wholesalePrice: '20000',
    minWholesaleQty: 5,
    stock: 35,
    unit: 'pcs',
    minStockAlert: 5,
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-4',
    organizationId: 'org-demo-1',
    outletId: 'outlet-1',
    name: 'Roti Bakar Cokelat Keju',
    sku: 'BAK-002',
    barcode: '899123456004',
    category: 'Makanan',
    costPrice: '9000',
    sellingPrice: '20000',
    wholesalePrice: '17000',
    minWholesaleQty: 5,
    stock: 40,
    unit: 'porsi',
    minStockAlert: 5,
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-5',
    organizationId: 'org-demo-1',
    outletId: 'outlet-1',
    name: 'Air Mineral 600ml',
    sku: 'BEV-003',
    barcode: '899123456005',
    category: 'Minuman',
    costPrice: '2500',
    sellingPrice: '5000',
    wholesalePrice: '4000',
    minWholesaleQty: 24,
    stock: 200,
    unit: 'botol',
    minStockAlert: 20,
    imageUrl: '',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const INITIAL_CUSTOMERS: Array<schema.Customer> = [
  {
    id: 'cust-1',
    organizationId: 'org-demo-1',
    name: 'Budi Santoso',
    phone: '081234567890',
    email: 'budi@example.com',
    address: 'Jl. Melati No. 12',
    loyaltyPoints: 150,
    totalSpent: '1500000',
    tier: 'GOLD',
    notes: 'Pelanggan tetap kopi pagi',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cust-2',
    organizationId: 'org-demo-1',
    name: 'Siti Aminah',
    phone: '081987654321',
    email: 'siti@example.com',
    address: 'Jl. Mawar No. 45',
    loyaltyPoints: 45,
    totalSpent: '450000',
    tier: 'SILVER',
    notes: 'Suka diskon member',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const INITIAL_SUPPLIERS: Array<schema.Supplier> = [
  {
    id: 'sup-1',
    organizationId: 'org-demo-1',
    name: 'PT Kopi Nusantara Jaya',
    contactPerson: 'Hendra Setiawan',
    phone: '081122334455',
    email: 'sales@kopinusantara.id',
    address: 'Kawasan Industri Bandung Blok C2',
    paymentTerms: 'TOP 14 Hari',
    createdAt: new Date(),
  },
  {
    id: 'sup-2',
    organizationId: 'org-demo-1',
    name: 'CV Dairy Prima Abadi',
    contactPerson: 'Dewi Lestari',
    phone: '081299887766',
    email: 'order@dairyprima.com',
    address: 'Jl. Raya Bogor KM 28',
    paymentTerms: 'Cash on Delivery',
    createdAt: new Date(),
  },
];
